# Generated by Django 4.2.6 on 2023-11-17 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'پشتیبانی', 'verbose_name_plural': 'پشتیبانی ها'},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='is_finished',
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='جواب داده شده؟'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='messages_history',
            field=models.JSONField(blank=True, default=[], null=True, verbose_name='پیام ها'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
