# Generated by Django 4.2.6 on 2023-10-30 00:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان محصول')),
                ('site_title', models.CharField(blank=True, max_length=400, null=True, verbose_name='عنوان صفحه')),
                ('site_meta_description', models.TextField(blank=True, null=True, verbose_name='متا دسکریپشن')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضحات محصول')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت محصول')),
                ('discounted_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت تخفیف خورده')),
                ('inventory', models.IntegerField(blank=True, null=True, verbose_name='موجودی')),
                ('specifications', models.JSONField(blank=True, null=True, verbose_name='مشخصات محصول')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='آدرس محصول')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('site_title_tag', models.CharField(blank=True, max_length=400, null=True, verbose_name='تگ تایتل')),
                ('site_meta_description', models.TextField(blank=True, null=True, verbose_name='متا دسکریپشن')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس دسته بندی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='product_app.productcategory', verbose_name='زیر مجموعه ی')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_title', models.CharField(max_length=100, verbose_name='رنگ به فارسی')),
                ('en_title', models.CharField(max_length=100, verbose_name='رنگ به انگلیسی')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/images')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='ویژگی')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=100, verbose_name='سایز')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='کد')),
                ('percentage', models.SmallIntegerField(verbose_name='درصد تخفیف')),
                ('expiration_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان انقضا')),
                ('category', models.ManyToManyField(blank=True, null=True, to='product_app.productcategory', verbose_name='برای دسته بندی')),
                ('products', models.ManyToManyField(blank=True, null=True, to='product_app.product', verbose_name='برای محصول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='برای کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.SmallIntegerField()),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_app.productcolor')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product_app.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_app.productsize')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product_app.productattribute', verbose_name='سایز بندی و رنگ بندی'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='product_app.productcategory', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='product_app.productimage', verbose_name='تصاویر محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='property',
            field=models.ManyToManyField(blank=True, null=True, to='product_app.productproperty', verbose_name='ویژگی ها'),
        ),
    ]
