# Generated by Django 4.2.6 on 2023-10-30 01:25

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_product_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscount',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='used_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد استفاده'),
        ),
    ]
