# Generated by Django 4.2.6 on 2023-10-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_productdiscount_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscount',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
