# Generated by Django 4.2.6 on 2023-10-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_productdiscount_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='در دسترس بودن'),
        ),
    ]
