# Generated by Django 4.2.6 on 2023-10-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_alter_productdiscount_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'خصوصیت محصول', 'verbose_name_plural': 'خصوصیات محصول'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسته بندی محصولات', 'verbose_name_plural': 'دسته بندی های محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'رنگ محصولات', 'verbose_name_plural': 'رنگ های محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productdiscount',
            options={'verbose_name': 'کد تخفیف محصولات', 'verbose_name_plural': 'کد های تخفیف محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'عکس محصولات', 'verbose_name_plural': 'عکس های محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productproperty',
            options={'verbose_name': 'ویژگی محصولات', 'verbose_name_plural': 'ویژگی های محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'سایز محصولات', 'verbose_name_plural': 'سایز های محصولات'},
        ),
    ]
