# Generated by Django 4.2.6 on 2023-10-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_alter_product_options_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(blank=True, null=True, to='product_app.product', verbose_name='محصولات')),
            ],
            options={
                'verbose_name': 'پیشنهاد ویژه',
                'verbose_name_plural': 'پیشنهادات ویژه',
            },
        ),
    ]
