# Generated by Django 4.2.6 on 2023-10-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_indexslideads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexslideads',
            options={'verbose_name': 'بنر اسلایدی صفحه اصلی', 'verbose_name_plural': 'بنر های اسلایدی صفحه اصلی'},
        ),
        migrations.AlterField(
            model_name='indexslideads',
            name='banner',
            field=models.ImageField(upload_to='index/slide_banner', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='indexslideads',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس'),
        ),
    ]
