# Generated by Django 4.2.6 on 2023-10-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_alter_indexslideads_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexDesctopBoxAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='index/slide_banner', verbose_name='تصویر')),
                ('url', models.URLField(blank=True, null=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'بنر باکسی دسکتاپ',
                'verbose_name_plural': 'بنر های باکسی دسکتاپ',
            },
        ),
        migrations.CreateModel(
            name='IndexMobileBoxAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='index/slide_banner', verbose_name='تصویر')),
                ('url', models.URLField(blank=True, null=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'بنر باکسی موبایل',
                'verbose_name_plural': 'بنر های باکسی موبایل',
            },
        ),
    ]
