# Generated by Django 4.2.6 on 2023-10-31 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_indexdesctopboxads_indexmobileboxads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexDesctopBoxAds',
            new_name='IndexDesktopBoxAds',
        ),
    ]
