# Generated by Django 4.2.6 on 2023-10-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0012_rename_indexdesctopboxads_indexdesktopboxads'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='products/posters', verbose_name='پوستر محصول'),
        ),
    ]
