# Generated by Django 4.2.6 on 2023-11-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0015_alter_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت محصول'),
        ),
    ]
