# Generated by Django 4.2.6 on 2023-11-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0018_product_sell_count_productattribute_sell_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان لیست')),
                ('products', models.ManyToManyField(to='product_app.product', verbose_name='انتخاب محصولات')),
            ],
            options={
                'verbose_name': 'لیست محصولات',
                'verbose_name_plural': 'لیست های محصولات',
            },
        ),
    ]
