# Generated by Django 4.2.6 on 2023-11-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0019_chosenproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosenproduct',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
