# Generated by Django 4.2.6 on 2023-11-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0022_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='منتشر شود؟'),
        ),
    ]
