# Generated by Django 4.2.6 on 2023-11-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0023_productcomment_is_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'verbose_name': 'دیدگاه محصول', 'verbose_name_plural': 'دیدگاه های محصول'},
        ),
    ]
