# Generated by Django 4.2.6 on 2023-11-06 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_app', '0024_alter_productcomment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.productcomment', verbose_name='دیگاه')),
                ('dislikes', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='دیسلایک ها')),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک ها')),
            ],
        ),
    ]
