# Generated by Django 4.2.6 on 2023-11-10 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0027_delete_productdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_app.productcolor', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='inventory',
            field=models.SmallIntegerField(verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product_app.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_app.productsize', verbose_name='سایزم'),
        ),
    ]
