# Generated by Django 4.2.6 on 2023-11-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0028_alter_productattribute_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_available', '-created_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
