# Generated by Django 4.2.6 on 2023-11-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoritem',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='رنگ'),
        ),
    ]
