# Generated by Django 4.2.6 on 2023-11-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_alter_factoritem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='is_create_by_admin',
            field=models.BooleanField(default=False, verbose_name='ساخته شده توسط ادمین؟'),
        ),
    ]
