# Generated by Django 4.2.6 on 2023-11-05 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0024_alter_productcomment_options'),
        ('order_app', '0003_factor_is_create_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product_app.productdiscount', verbose_name='کد تخفیف اعمال شده'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='discounted_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه ی تخفیف خورده'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه ی فاکتور'),
        ),
    ]
