# Generated by Django 4.2.6 on 2023-11-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_alter_factor_discount_alter_factor_discounted_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoritem',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='سایز'),
        ),
    ]
