# Generated by Django 4.2.6 on 2023-11-08 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_app', '0007_alter_order_options_factordiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order_app.factordiscount', verbose_name='کد تخفیف اعمال شده'),
        ),
        migrations.AlterField(
            model_name='factordiscount',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='factor_discounts', to=settings.AUTH_USER_MODEL, verbose_name='برای کاربران'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order_app.factordiscount', verbose_name='کد تخفیف اعمال شده'),
        ),
    ]
