# Generated by Django 4.2.6 on 2023-11-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_alter_address_options'),
        ('order_app', '0011_factor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_app.address', verbose_name='آدرس'),
        ),
    ]
