# Generated by Django 4.2.6 on 2023-11-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0012_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='is_create_by_admin',
        ),
    ]
