# Generated by Django 4.2.6 on 2023-11-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0014_order_unique_id_alter_order_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_id',
            field=models.CharField(max_length=20, null=True, verbose_name='کد سفارش'),
        ),
    ]
