# Generated by Django 4.2.6 on 2023-11-10 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0015_alter_order_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=200, verbose_name='دلیل مرجوع کردن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='order_referral', verbose_name='تصویر مریوطه')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='order_app.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'مرجوع',
                'verbose_name_plural': 'مرجوعی ها',
            },
        ),
    ]
