# Generated by Django 4.2.6 on 2023-11-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0016_orderreferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='month',
            field=models.IntegerField(default=0, verbose_name='ماه'),
        ),
        migrations.AddField(
            model_name='order',
            name='year',
            field=models.IntegerField(default=0, verbose_name='سال'),
        ),
    ]
