# Generated by Django 4.2.6 on 2023-11-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0017_order_month_order_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='factordiscount',
            name='max_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تا سقف'),
        ),
    ]
