# Generated by Django 4.2.6 on 2023-11-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0018_factordiscount_max_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='day',
            field=models.IntegerField(default=0, verbose_name='روز'),
        ),
    ]
