# Generated by Django 4.2.6 on 2023-11-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0019_order_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hour',
            field=models.IntegerField(default=0, editable=False, verbose_name='ساعت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='day',
            field=models.IntegerField(default=0, editable=False, verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.IntegerField(default=0, editable=False, verbose_name='ماه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='year',
            field=models.IntegerField(default=0, editable=False, verbose_name='سال'),
        ),
    ]
