# Generated by Django 4.2.6 on 2023-11-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0020_order_hour_alter_order_day_alter_order_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day',
            field=models.IntegerField(default=0, verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hour',
            field=models.IntegerField(default=0, verbose_name='ساعت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.IntegerField(default=0, verbose_name='ماه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='year',
            field=models.IntegerField(default=0, verbose_name='سال'),
        ),
    ]
