# Generated by Django 4.2.6 on 2023-11-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0021_alter_order_day_alter_order_hour_alter_order_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
    ]
