# Generated by Django 4.2.6 on 2023-11-17 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_app', '0022_order_send_sms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.factordiscount', verbose_name='انتخاب کد تخفیف')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='انتخاب کاربر ها')),
            ],
            options={
                'verbose_name': 'اس ام اس تخفیف',
                'verbose_name_plural': 'اس ام اس های تخفیف',
            },
        ),
    ]
