# Generated by Django 4.2.6 on 2023-12-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0026_factordiscount_use'),
        ('sms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountsms',
            name='is_for_all',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ارسال برای همه'),
        ),
        migrations.AlterField(
            model_name='discountsms',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_app.factordiscount', verbose_name='انتخاب کد تخفیف'),
        ),
    ]
