# Generated by Django 4.2.6 on 2023-12-05 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms_app', '0002_discountsms_is_for_all_alter_discountsms_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountsms',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='انتخاب کاربر ها'),
        ),
    ]
