# Generated by Django 4.2.6 on 2023-11-03 04:01

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='remove_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='زمان حذف'),
        ),
    ]
