# Generated by Django 4.2.6 on 2023-11-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
    ]
