# Generated by Django 4.2.6 on 2023-12-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0025_alter_order_day_alter_order_hour_alter_order_month_and_more'),
        ('profile_app', '0005_alter_address_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مقدار جایزه')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.factordiscount', verbose_name='کد تخفیف')),
            ],
            options={
                'verbose_name': 'جایزه',
                'verbose_name_plural': 'جایزه ها',
            },
        ),
    ]
