# Generated by Django 4.2.6 on 2023-10-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_app', '0010_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadableArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.ManyToManyField(blank=True, null=True, to='blog_app.article', verbose_name='مقالات')),
            ],
            options={
                'verbose_name': 'مطلب خواندنی',
                'verbose_name_plural': 'مطالب خواندنی',
            },
        ),
    ]
