# Generated by Django 4.2.6 on 2023-11-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0003_alter_sitevisit_browser_alter_sitevisit_ip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisit',
            options={'verbose_name': 'آمار بازدید', 'verbose_name_plural': 'آمار های بازدید'},
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
