# Generated by Django 4.2.6 on 2023-11-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0004_alter_sitevisit_options_alter_sitevisit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
