# Generated by Django 4.2.6 on 2023-11-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0006_sitevisit_month_alter_sitevisit_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
