# Generated by Django 4.2.6 on 2023-11-11 05:09

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0007_alter_sitevisit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
