# Generated by Django 4.2.6 on 2023-12-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0008_alter_sitevisit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='month',
            field=models.IntegerField(default=0, editable=False, verbose_name='ماه'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='year',
            field=models.IntegerField(default=0, editable=False, verbose_name='سال'),
        ),
    ]
