# Generated by Django 4.2.6 on 2023-11-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_alter_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day',
            field=models.IntegerField(default=0, verbose_name='روز'),
        ),
        migrations.AddField(
            model_name='user',
            name='hour',
            field=models.IntegerField(default=0, verbose_name='ساعت'),
        ),
        migrations.AddField(
            model_name='user',
            name='month',
            field=models.IntegerField(default=0, verbose_name='ماه'),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(default=0, verbose_name='سال'),
        ),
    ]
