# Generated by Django 4.2.6 on 2023-11-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_ban'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ban',
            options={'verbose_name': 'مسدود', 'verbose_name_plural': 'مسدود ها'},
        ),
    ]
