# Generated by Django 4.2.6 on 2023-12-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0008_alter_ban_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prize_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار جایزه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='day',
            field=models.IntegerField(default=0, editable=False, verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hour',
            field=models.IntegerField(default=0, editable=False, verbose_name='ساعت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='month',
            field=models.IntegerField(default=0, editable=False, verbose_name='ماه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(default=0, editable=False, verbose_name='سال'),
        ),
    ]
