# Generated by Django 4.2.6 on 2023-10-27 23:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('site_title_tag', models.CharField(blank=True, max_length=400, null=True, verbose_name='تگ تایتل')),
                ('site_meta_description', models.TextField(blank=True, null=True, verbose_name='متا دسکریپشن')),
                ('unique_visitors', models.TextField(default='')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس دسته بندی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='blog_app.articlecategory', verbose_name='زیر مجموعه ی')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان مقاله')),
                ('site_title_tag', models.CharField(blank=True, max_length=400, null=True, verbose_name='تگ تایتل')),
                ('site_meta_description', models.TextField(blank=True, null=True, verbose_name='متا دسکریپشن')),
                ('visit_count', models.PositiveBigIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('unique_visitors', models.TextField(default='')),
                ('poster', models.ImageField(upload_to='articles/posters', verbose_name='پوستر مقاله')),
                ('body', ckeditor.fields.RichTextField(verbose_name='متن مقاله')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده ی مقاله')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='blog_app.articlecategory', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
