# Generated by Django 4.2.6 on 2023-10-28 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_article_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategory',
            name='unique_visitors',
        ),
    ]
