# Generated by Django 4.2.6 on 2023-10-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_remove_articlecategory_unique_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unique_visitors',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
