# Generated by Django 4.2.6 on 2023-10-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_article_unique_visitors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'دسته بندی مقالات', 'verbose_name_plural': 'دسته بندی های مقالات'},
        ),
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
