# Generated by Django 4.2.6 on 2023-10-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_blogads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogads',
            options={'verbose_name': 'عکس تبلیغ بلاگ', 'verbose_name_plural': 'عکس تبلیغ بلاگ ها'},
        ),
        migrations.AddField(
            model_name='blogads',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
