# Generated by Django 4.2.6 on 2023-10-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_blogads_options_blogads_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogads',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک تبلیغ'),
        ),
        migrations.CreateModel(
            name='ArticleSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.ManyToManyField(to='blog_app.article', verbose_name='انتخاب مقالات')),
            ],
        ),
    ]
