# Generated by Django 4.2.6 on 2023-10-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_blogads_url_articleslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_articles', models.ManyToManyField(blank=True, null=True, related_name='slides', to='blog_app.article', verbose_name='انتخاب مقالات اسلایدی')),
                ('two_articles', models.ManyToManyField(blank=True, null=True, related_name='two', to='blog_app.article', verbose_name='انتخاب دو مقاله')),
            ],
            options={
                'verbose_name': 'مقاله انتخابی',
                'verbose_name_plural': 'مقالات انتخابی',
            },
        ),
        migrations.DeleteModel(
            name='ArticleSlide',
        ),
    ]
