# Generated by Django 4.2.6 on 2023-10-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_articlechoose_delete_articleslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='آدرس مقاله'),
        ),
    ]
